// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Fix_Users : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "pk_user",
                schema: "dev_habit",
                table: "user");

            migrationBuilder.RenameTable(
                name: "user",
                schema: "dev_habit",
                newName: "users",
                newSchema: "dev_habit");

            migrationBuilder.RenameIndex(
                name: "ix_user_identity_id",
                schema: "dev_habit",
                table: "users",
                newName: "ix_users_identity_id");

            migrationBuilder.RenameIndex(
                name: "ix_user_email",
                schema: "dev_habit",
                table: "users",
                newName: "ix_users_email");

            migrationBuilder.AddPrimaryKey(
                name: "pk_users",
                schema: "dev_habit",
                table: "users",
                column: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "pk_users",
                schema: "dev_habit",
                table: "users");

            migrationBuilder.RenameTable(
                name: "users",
                schema: "dev_habit",
                newName: "user",
                newSchema: "dev_habit");

            migrationBuilder.RenameIndex(
                name: "ix_users_identity_id",
                schema: "dev_habit",
                table: "user",
                newName: "ix_user_identity_id");

            migrationBuilder.RenameIndex(
                name: "ix_users_email",
                schema: "dev_habit",
                table: "user",
                newName: "ix_user_email");

            migrationBuilder.AddPrimaryKey(
                name: "pk_user",
                schema: "dev_habit",
                table: "user",
                column: "id");
        }
    }
}
