name: Build

on:
  workflow_dispatch:
  push: 
    branches:
      - main
        
env:
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "DevHabit.sln"
  
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build