name: API CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: myko-devhabit-api
  AZURE_WEBAPP_PACKAGE_PATH: ./DevHabit.Api/publish
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: DevHabit.sln
  API_PROJECT_PATH: DevHabit.Api
  PUBLISH_DIR: ./publish
  CONNECTIONSTRINGS__DATABASE: '<Replaced by Bundle>'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp #artifact name
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    

  apply-migrations:
    name: Apply Database Migrations
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Add EF tool to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Create migration bundle
        run: |
          dotnet ef migrations bundle --startup-project ${{ env.API_PROJECT_PATH }} --project ${{ env.API_PROJECT_PATH }} --context ApplicationDbContext --output app-bundle.exe
          dotnet ef migrations bundle --startup-project ${{ env.API_PROJECT_PATH }} --project ${{ env.API_PROJECT_PATH }} --context ApplicationIdentityDbContext --output identity-bundle.exe

      - name: Apply app migration
        run: ./app-bundle.exe --connection "${{ secrets.DATABASE_CONNECTION_STRING }}"

      - name: Apply identity migration
        run: ./identity-bundle.exe --connection "${{ secrets.DATABASE_CONNECTION_STRING }}"

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test, apply-migrations] # array of dependent jobs

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
