name: API CI

on:
  workflow_dispatch:
  push: 
    branches:
      - main
        
env:
  AZURE_WEBAPP_NAME: myko-devhabit-api  
  AZURE_WEBAPP_PACKAGE_PATH: "./DevHabit.Api/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "DevHabit.sln"
  API_PROJECT_PATH: "DevHabit.Api"  
  PUBLISH_DIR: "./publish"
  CONNECTIONSTRINGS__DATABASE: "<Replaced by Bundle>"
  
  
jobs: 
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp #artifact name
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}